name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Never cancel in progress jobs to ensure code is deployed
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  run-tests:
    name: Tests
    uses: ./.github/workflows/test.yaml

  publish:
    name: Publish Extension
    needs: [run-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FORCE_COLOR: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.KONGPONENTS_BOT_PAT }}

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/

      - name: Set up git user
        run: |
          git config user.name 'kong-ui[bot]'
          git config user.email "konnectx-engineers+kongponents-bot@konghq.com"

      - name: Version the extension and generate changelog
        id: version
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
        run: |
          # Version the extension, update the CHANGELOG.md, and create the git tag
          pnpm release

          # Extract version from package.json and set as step output
          VERSION=$(jq -r '.version' package.json)
          echo "New version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Pull in latest main branch changes
          git pull --rebase --tags origin main

          # Push changes to main branch
          git push origin main --follow-tags

      - name: Build extension package
        # TODO: Eventually remove --pre-release flag when ready for stable releases
        run: pnpm package --pre-release

      - name: Publish extension to VS Code marketplace
        if: ${{ steps.version.outputs.version != '' }}
        env:
          VSCE_PAT: ${{ secrets.AZURE_DEVOPS_MARKETPLACE_PUBLISH_TOKEN }}
        # TODO: Eventually remove --pre-release flag when ready for stable releases
        run: |
          pnpm vsce publish ${{ steps.version.outputs.version }} \
            --pre-release \
            --no-update-package-json \
            --no-git-tag-version

      - name: Publish to Open VSX Registry
        env:
          OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}
        run: |
          pnpm ovsx publish \
          --packageVersion ${{ steps.version.outputs.version }} \
          --pre-release \
          *.vsix

      - name: Create GitHub Release
        if: ${{ steps.version.outputs.version != '' }}
        env:
          GH_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
        run: |
          # Pull in latest main branch changes
          git fetch --tags

          # Confirm tag exists
          git tag -l "v${{ steps.version.outputs.version }}"

          # Create GitHub Release using the generated tag and changelog
          gh release create "v${{ steps.version.outputs.version }}" \
            --title "v${{ steps.version.outputs.version }}" \
            --notes-from-tag
