name: Tests

on:
  pull_request:

  # Allow workflow to be called by another workflow
  workflow_call:

  # Allow calling manually from GitHub
  workflow_dispatch:

jobs:
  test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/
        with:
          force-install: true
          save-cache: true

      - name: Lint
        run: pnpm -r lint

      - name: Typecheck
        run: pnpm -r typecheck

      - name: Run all tests
        run: pnpm test

  build:
    name: Build extension
    runs-on: ubuntu-latest
    needs: [test]
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/

      - name: Build Extension
        run: |
          pnpm build

      # - name: Upload extension build artifacts
      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      #   with:
      #     name: extension-build-output-artifact
      #     path: |
      #       apps/portal
      #       !apps/portal/node_modules/**
      #     include-hidden-files: 'true'
